#!/bin/sh

# enable XDG autostart
/usr/bin/dex -a &

# enable xscreensaver and lock screen
#/usr/bin/sleep 1 && /usr/bin/xscreensaver -nosplash &
#/usr/bin/sleep 1 && /usr/bin/xss-lock -- /usr/bin/xscreensaver-command -lock &

# start pulseaudio audio GUI tray
/usr/bin/sleep 1 && /usr/bin/pnmixer &

# start nm-applet
/usr/bin/sleep 1 && /usr/bin/nm-applet &

# start thunar in daemon mode
/usr/bin/thunar --daemon
