#!/bin/sh

# enable XDG autostart
/usr/bin/dex -a &

# enable screensaver
/usr/bin/xscreensaver --nosplash &

# start pulseaudio audio GUI tray
/usr/bin/sleep 1 && /usr/bin/pnmixer &

# start nm-applet
/usr/bin/sleep 1 && /usr/bin/nm-applet &

# start thunar in daemon mode
/usr/bin/thunar --daemon
